- debug para el siguiente error
Assets\SCRIPTS\SCENE CONTROLLER\NEXTSCENE.cs(29,9): error CS0119: 'Object.Destroy(Object, float)' is a method, which is not valid in the given context